### ISSUE TITLE
Cannot get it to run. 

### ISSUE THREAD

**Issue by steven-starling** [sonatype-nexus-community/nexusiq-successmetrics#100]
On windows and on linux, I keep getting the same " Unable to access jarfile get-metrics-@APPVER@.jar" error

**Comment by steven-starling** [comment]
Now, we get the following: 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.6.12)

2022-11-01 15:21:46.498  INFO 96187 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : Starting GetMetricsApplication using Java 1.8.0_342 on lassonaprd01iq01.fnbm.corp with PID 96187 (/home/sstarling/nexusiq-successmetrics-98/nexusiq-successmetrics-98/get-metrics/get-metrics-98.jar started by root in /home/sstarling/nexusiq-successmetrics-98/nexusiq-successmetrics-98/get-metrics)
2022-11-01 15:21:46.500  INFO 96187 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : No active profile set, falling back to 1 default profile: "default"
2022-11-01 15:21:46.996  INFO 96187 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : Started GetMetricsApplication in 0.879 seconds (JVM running for 1.309)
2022-11-01 15:21:46.999  INFO 96187 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : Starting GetMetrics Application
2022-11-01 15:21:47.001  INFO 96187 --- [           main] o.s.c.g.service.NexusIQSuccessMetrics    : Making api payload
2022-11-01 15:21:47.004  INFO 96187 --- [           main] o.s.c.g.service.NexusIQSuccessMetrics    : Api Payload: {"timePeriod":"WEEK","firstTimePeriod":"2020-01"}
2022-11-01 15:21:47.236  INFO 96187 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-11-01 15:21:47.262 ERROR 96187 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:785) [spring-boot-2.6.12.jar!/:2.6.12]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:766) [spring-boot-2.6.12.jar!/:2.6.12]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.6.12.jar!/:2.6.12]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) [spring-boot-2.6.12.jar!/:2.6.12]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-2.6.12.jar!/:2.6.12]
        at org.sonatype.cs.getmetrics.GetMetricsApplication.main(GetMetricsApplication.java:57) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_342]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_342]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_342]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_342]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [get-metrics-98.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [get-metrics-98.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [get-metrics-98.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [get-metrics-98.jar:na]
Caused by: org.apache.http.HttpException: Failed with HTTP error code : 400 [Bad Request]
        at org.sonatype.cs.getmetrics.service.NexusIqApiConnectionService.executeHttpURLPostForCSV(NexusIqApiConnectionService.java:97) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.service.NexusIqApiConnectionService.retrieveCsvBasedOnPayload(NexusIqApiConnectionService.java:83) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.service.NexusIQSuccessMetrics.createSuccessMetricsCsvFile(NexusIQSuccessMetrics.java:67) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.GetMetricsApplication.run(GetMetricsApplication.java:72) [classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782) [spring-boot-2.6.12.jar!/:2.6.12]
        ... 13 common frames omitted

**Comment by steven-starling** [comment]
We are using vm's that were using locally-signed. However, we are now testing a vm that uses http and getting the same error messages.

**Comment by caw916** [comment]
Steven was able to determine the problem.  The iq.api.sm.period needs to match the iq.api.sm.payload selection.  In the latter, the "W" is the difference.  If these don't match you get the errors that Steven posted.

Can an error msg be generated that lets the user know to check these settings?

**Comment by rpanman-sonatype** [comment]
This change is now merged into the develop branch and so will be part of the next release (should be version 100).
