### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by awoodobvio** [sonatype-nexus-community/nexusiq-successmetrics#108]
Version 99
Running in windows 10 using **runapp-docker.bat**

----------------------------------------------

Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:785) [spring-boot-2.6.12.jar!/:2.6.12]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:766) [spring-boot-2.6.12.jar!/:2.6.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.6.12.jar!/:2.6.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) [spring-boot-2.6.12.jar!/:2.6.12]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-2.6.12.jar!/:2.6.12]
	at org.sonatype.cs.getmetrics.GetMetricsApplication.main(GetMetricsApplication.java:57) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [app.jar:na]
Caused by: org.apache.http.HttpException: Failed with HTTP error code : 401 [Unauthorized]
	at org.sonatype.cs.getmetrics.service.NexusIqApiConnectionService.executeHttpURLPostForCSV(NexusIqApiConnectionService.java:97) ~[classes!/:na]
	at org.sonatype.cs.getmetrics.service.NexusIqApiConnectionService.retrieveCsvBasedOnPayload(NexusIqApiConnectionService.java:83) ~[classes!/:na]
	at org.sonatype.cs.getmetrics.service.NexusIQSuccessMetrics.createSuccessMetricsCsvFile(NexusIQSuccessMetrics.java:67) ~[classes!/:na]
	at org.sonatype.cs.getmetrics.GetMetricsApplication.run(GetMetricsApplication.java:72) [classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782) [spring-boot-2.6.12.jar!/:2.6.12]
	... 13 common frames omitted

**Comment by awoodobvio** [comment]
Just noticed the 401.  Going to track down the un/pw problem on my side.

**Comment by awoodobvio** [comment]
I've been trying to log in using a user token (due to SSO accounts) but I can't seem to get it to work.  

Does this tool support user tokens?

**Comment by awoodobvio** [comment]
Doesn't work with a user created in our IQ system either.

However, a CURL statement using the same credentials against **/api/v2/reports/metrics** works fine.

**Comment by rpanman-sonatype** [comment]
The 401 response is direct from IQ so it's definitely authentication. You're right that you should use token credentials and it's great that you've checked with curl already, so we know the credentials are good.

What I've seen before is that sometimes there are spaces at the end of the password or username fields, or that they are surrounded by quotes. Would you mind double-checking?

**Comment by awoodobvio** [comment]
No spaces.  There were quotes - but they were added to try to get around this problem.  Removed them and it resulted in the same problem.

**Comment by awoodobvio** [comment]
Tried the CLI method:

./runapp-docker.bat --iq.url=<IQ URL> --iq.user=<IQ Username> --iq.passwd=<IQ Password> 

Still no luck.

**Comment by awoodobvio** [comment]
This was (as expected) user error.  I recreated the user and password and was able to successfully pull the metrics.  I'm closing this as "not a problem".
