### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by mustafakapasi** [sonatype-nexus-community/nexusiq-successmetrics#126]
Hi, The .\get-metrics\runapp.bat or .\get-metrics\runapp..sh files most of the time, but does succeed some times.
The error is a 504 gateway timeout. Is the timeout setting configurable ?

Stack Trace here : 
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.7.18)

2024-04-23 10:22:39.512  INFO 11768 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : Starting GetMetricsApplication using Java 1.8.0_281 on **** with PID **** (C:\Users\****\Desktop\nexusiq-successmetrics-105\get-metrics\get-metrics-105.jar started by **** in C:\Users\****\Desktop\nexusiq-successmetrics-105\get-metrics)
2024-04-23 10:22:39.515  INFO 11768 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : No active profile set, falling back to 1 default profile: "default"
2024-04-23 10:22:40.129  INFO 11768 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : Started GetMetricsApplication in 1.104 seconds (JVM running for 1.803)
2024-04-23 10:22:40.132  INFO 11768 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : Starting GetMetrics Application
2024-04-23 10:22:40.140  INFO 11768 --- [           main] o.s.c.g.service.NexusIQSuccessMetrics    : Making api payload
2024-04-23 10:22:40.144  INFO 11768 --- [           main] o.s.c.g.service.NexusIQSuccessMetrics    : Api Payload: {"timePeriod":"WEEK","firstTimePeriod":"2023-W01"}
2024-04-23 10:23:11.064  INFO 11768 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-04-23 10:23:11.102 ERROR 11768 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768) [spring-boot-2.7.18.jar!/:2.7.18]
        at org.springframework.boot.SpringApplication.lambda$callRunners$2(SpringApplication.java:749) [spring-boot-2.7.18.jar!/:2.7.18]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:1.8.0_281]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[na:1.8.0_281]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_281]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_281]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_281]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_281]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_281]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_281]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:744) [spring-boot-2.7.18.jar!/:2.7.18]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.7.18.jar!/:2.7.18]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.7.18.jar!/:2.7.18]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) [spring-boot-2.7.18.jar!/:2.7.18]
        at org.sonatype.cs.getmetrics.GetMetricsApplication.main(GetMetricsApplication.java:57) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_281]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_281]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_281]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_281]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [get-metrics-105.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [get-metrics-105.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [get-metrics-105.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) [get-metrics-105.jar:na]
Caused by: org.apache.http.HttpException: Failed with HTTP error code : 504 [Gateway Time-out]
        at org.sonatype.cs.getmetrics.service.NexusIqApiConnectionService.executeHttpURLPostForCSV(NexusIqApiConnectionService.java:97) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.service.NexusIqApiConnectionService.retrieveCsvBasedOnPayload(NexusIqApiConnectionService.java:83) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.service.NexusIQSuccessMetrics.createSuccessMetricsCsvFile(NexusIQSuccessMetrics.java:84) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.GetMetricsApplication.run(GetMetricsApplication.java:72) [classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765) [spring-boot-2.7.18.jar!/:2.7.18]
        ... 22 common frames omitted


```

**Comment by mustafakapasi** [comment]
Since we were running nexus on openshift, I increased the route timeout to 5 mins by adding this annotation to the route
annotations : 
        haproxy.router.openshift.io/timeout: 5m
     
 Not getting timeout errors anymore.
