### ISSUE TITLE
Docs: How should 'debug' be enabled?

### ISSUE THREAD

**Issue by bcdady** [sonatype-nexus-community/nexusiq-successmetrics#28]
I've encountered this error, but I cannot yet find any code or config for enabling 'debug'.

Is it supported to add an argument in the ./config/application.properties file to enable debug output?

```java
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
```

In case it helps, here is the full output I collected (was run from container image 'ghcr.io/sonatype-nexus-community/nexusiq-successmetrics:89')

```java
2022-02-22 03:30:36.744  INFO 50 --- [           main] o.s.c.metrics.SuccessMetricsApplication  : Starting SuccessMetricsApplication using Java 1.8.0_212 on 51a0b7a9f44d with PID 50 (/app.jar started by root in /)
2022-02-22 03:30:36.811  INFO 50 --- [           main] o.s.c.metrics.SuccessMetricsApplication  : The following profiles are active: web
2022-02-22 03:30:49.637  INFO 50 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-02-22 03:30:49.855  INFO 50 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 87 ms. Found 0 JPA repository interfaces.
2022-02-22 03:31:01.710  INFO 50 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 4040 (http)
2022-02-22 03:31:01.871  INFO 50 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-02-22 03:31:01.881  INFO 50 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.54]
2022-02-22 03:31:03.027  INFO 50 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-02-22 03:31:03.049  INFO 50 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 25459 ms
2022-02-22 03:31:06.507  INFO 50 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-02-22 03:31:11.459  INFO 50 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-02-22 03:31:11.739  INFO 50 --- [           main] o.s.b.a.h2.H2ConsoleAutoConfiguration    : H2 console available at '/db'. Database available at 'jdbc:h2:mem:testdb'
2022-02-22 03:31:16.557  INFO 50 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-02-22 03:31:17.777  INFO 50 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.32.Final
2022-02-22 03:31:20.629  INFO 50 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-02-22 03:31:22.973  INFO 50 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2022-02-22 03:31:33.348  INFO 50 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-02-22 03:31:33.495  INFO 50 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-02-22 03:31:47.020  INFO 50 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-02-22 03:31:47.746  INFO 50 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 4040 (http) with context path ''
2022-02-22 03:31:47.978  INFO 50 --- [           main] o.s.c.metrics.SuccessMetricsApplication  : Started SuccessMetricsApplication in 78.139 seconds (JVM running for 84.608)
2022-02-22 03:31:48.551  INFO 50 --- [           main] o.s.c.metrics.SuccessMetricsApplication  : Run mode: SERVLET
2022-02-22 03:31:48.557  INFO 50 --- [           main] o.s.c.metrics.SuccessMetricsApplication  : Working directory: /
2022-02-22 03:31:48.563  INFO 50 --- [           main] o.s.c.metrics.SuccessMetricsApplication  : Active profile: web
2022-02-22 03:31:48.570  INFO 50 --- [           main] o.s.cs.metrics.service.LoaderService     : Creating successmetrics.csv file
2022-02-22 03:31:48.576  INFO 50 --- [           main] o.s.cs.metrics.service.LoaderService     : Making api payload
2022-02-22 03:31:48.634  INFO 50 --- [           main] o.s.cs.metrics.service.LoaderService     : Api Payload: {"timePeriod":"MONTH","lastTimePeriod":"2021-12","firstTimePeriod":"2021-07"}
2022-02-22 03:31:51.988  INFO 50 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-02-22 03:31:52.258 ERROR 50 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) ~[spring-boot-2.5.6.jar!/:2.5.6]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) ~[spring-boot-2.5.6.jar!/:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.6.jar!/:2.5.6]
	at org.sonatype.cs.metrics.SuccessMetricsApplication.main(SuccessMetricsApplication.java:60) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [app.jar:na]
Caused by: java.lang.RuntimeException: Failed with HTTP error code : 400
	at org.sonatype.cs.metrics.service.LoaderService.createSmDatafile(LoaderService.java:266) ~[classes!/:na]
	at org.sonatype.cs.metrics.SuccessMetricsApplication.run(SuccessMetricsApplication.java:70) [classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) ~[spring-boot-2.5.6.jar!/:2.5.6]
	... 11 common frames omitted

2022-02-22 03:31:52.877  INFO 50 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-02-22 03:31:52.885  INFO 50 --- [           main] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2022-02-22 03:31:52.992  INFO 50 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-02-22 03:31:53.136  INFO 50 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

**Comment by rpanman-sonatype** [comment]
Hey @bcdady 

On an application level the logging that you see on the screen is the extent of the logging available. There's some additional SpringBoot framework logging available which can tell us about the environment in which the jar is running, but that isn't the problem in your case.

On the 400 error message, let's continue to discuss that under #29.

**Comment by rpanman-sonatype** [comment]
As of release 90 the reason text received from IQ in case of a failure is now shown in the logs to help give some more diagnosis, so I'm closing this ticket here for now.
