### ISSUE TITLE
Need more info in error message "Failed with HTTP error code : 400"

### ISSUE THREAD

**Issue by bcdady** [sonatype-nexus-community/nexusiq-successmetrics#29]
I've followed the instructions in the README for running the success metrics report via container image (Release 89).

I've successfully used the previous (python) edition of the success metrics reporting with these same credentials, so I have no reason to suspect that there are any interferences of an environmental/network or authentication nature.

I edited the docker `entrypoint` and ran `java -jar app.jar --debug`, but it simply outputs the same level of `Application run failed` detail as is available without `--debug`. 

How can a user get the additional information needed to troubleshoot and resolve the cause of the "HTTP error code : 400"?

Here is the pertinent snippet:

```java
2022-02-22 03:44:23.816 ERROR 106 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794) ~[spring-boot-2.5.6.jar!/:2.5.6]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775) ~[spring-boot-2.5.6.jar!/:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.6.jar!/:2.5.6]
	at org.sonatype.cs.metrics.SuccessMetricsApplication.main(SuccessMetricsApplication.java:60) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [app.jar:na]
Caused by: java.lang.RuntimeException: Failed with HTTP error code : 400
	at org.sonatype.cs.metrics.service.LoaderService.createSmDatafile(LoaderService.java:266) ~[classes!/:na]
	at org.sonatype.cs.metrics.SuccessMetricsApplication.run(SuccessMetricsApplication.java:70) [classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) ~[spring-boot-2.5.6.jar!/:2.5.6]
	... 11 common frames omitted
```

**Comment by rpanman-sonatype** [comment]
Hey @bcdady, Sorry for the delay in getting in touch. In general 400 is "bad request" which would most likely mean that the payload is malformed in some way. Would you be able to share the following parameters from your applications.properties file?
```
# mandatory: week, month
iq.sm.period=???

# mandatory: example: week=2019-W01, month=2019-01
iq.api.payload.timeperiod.first=???

# optional
iq.api.payload.timeperiod.last=???

# optional: set one of the two below
# if both omitted, all organisations/applications will apply
# if both set, organisation will take precedence
iq.api.payload.organisation.name=???
iq.api.payload.application.name=???
```

**Comment by bcdady** [comment]
Sure thing. Here is my application.properties file (secrets redacted):

```java
# user properties

# web, pdf, insights
spring.profiles.active=web
# spring.profiles.active=pdf
# spring.profiles.active=insights

# directory in which zip file is unzipped ie. the working directory
# to load the csv files from another location, set it here
data.dir=.

# will be sub-directory of data.dir
reports.outputdir=output

# the latest period is the period when you run the application. It is likely it has not ended, therefore data for the period will be incomplete.
# by default, the application will exclude the period from the report.
# to include data for the latest period, set the following property:
# data.includelatestperiod=false

data.loadInsightsMetrics=true

# if this is set to true, the following properties must be set
# if set to true, the application will automatically extract the required success metrics data from Nexus IQ into the required successmetrics.csv.
# for very large IQ instances, we recommend to always set an organisation or application name when setting this to true, to minimise amount of data extracted from Nexus IQ.
iq.sm.csvfile=true

# Set Nexus IQ Url
# If running the docker image, use this value
#  iq.url=http://host.docker.internal:8070

iq.url=http://nexusiq.subsplash.net:8070

# Set Nexus IQ user and password
# WARNING : DO NOT COMMIT THESE SECRETS
iq.user=gitlab-runner
iq.pwd=*****************

# mandatory: week, month
iq.sm.period=month

# mandatory: example: week=2019-W01, month=2019-01
iq.api.payload.timeperiod.first=2021-07

# optional
iq.api.payload.timeperiod.last=2021-12

# optional: set one of the two below
# if both omitted, all organisations/applications will apply
# if both set, organisation will take precedence
# iq.api.payload.organisation.name=
# iq.api.payload.application.name=
```

**Comment by bcdady** [comment]
I just figured it out. It was the URL schema.
I changed the `iq.url` from `http` to `https`, and now it's working.
