### ISSUE TITLE
400 error from jar

### ISSUE THREAD

**Issue by lexbernier** [sonatype-nexus-community/nexusiq-successmetrics#42]
Unclear as to issue, I've tried IQ tokens, and just admin and password. No luck. In ver 85 I do not see this issue. Do you have any suggestions?
I know with iq-cli.exe on windows I had to pass the certs for my IQ server. But no mention in your docs on needing to do that.

Any help would be appreciated

"Stuck on 85"

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.3)

2022-03-18 13:43:04.398  INFO 27532 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : Starting GetMetricsApplication using Java 17.0.1 on FBERNIER33 with PID 27532 (D:\Lifecycle\nexusiq-successmetrics-90\get-metrics\get-metrics-90.jar started by fbernier in D:\Lifecycle\nexusiq-successmetrics-90\get-metrics)
2022-03-18 13:43:04.410  INFO 27532 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : No active profile set, falling back to default profiles: default
2022-03-18 13:43:06.094  INFO 27532 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : Started GetMetricsApplication in 3.702 seconds (JVM running for 7.7)
2022-03-18 13:43:06.100  INFO 27532 --- [           main] o.s.cs.getmetrics.GetMetricsApplication  : Starting GetMetrics Application
2022-03-18 13:43:06.104  INFO 27532 --- [           main] o.s.c.g.service.NexusIQSuccessMetrics    : Making api payload
2022-03-18 13:43:06.111  INFO 27532 --- [           main] o.s.c.g.service.NexusIQSuccessMetrics    : Api Payload: {"timePeriod":"WEEK","lastTimePeriod":"\"2022-W11\"","firstTimePeriod":"\"2022-W04\""}
2022-03-18 13:43:06.599  INFO 27532 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-18 13:43:06.682 ERROR 27532 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:753) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:309) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.sonatype.cs.getmetrics.GetMetricsApplication.main(GetMetricsApplication.java:43) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[get-metrics-90.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[get-metrics-90.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[get-metrics-90.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[get-metrics-90.jar:na]
Caused by: org.apache.http.HttpException: Failed with HTTP error code : 400 [Bad Request]
        at org.sonatype.cs.getmetrics.util.NexusIqApiConnection.executeHttpURLPostForCSV(NexusIqApiConnection.java:97) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.util.NexusIqApiConnection.retrieveCsvBasedOnPayload(NexusIqApiConnection.java:83) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.service.NexusIQSuccessMetrics.createSuccessMetricsCsvFile(NexusIQSuccessMetrics.java:66) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.GetMetricsApplication.run(GetMetricsApplication.java:53) ~[classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:769) ~[spring-boot-2.6.3.jar!/:2.6.3]
        ... 13 common frames omitted

**Comment by lexbernier** [comment]
After reviewing previos email I adjust my iq.url=https://san-stiq-prod.cscr.hp.com:8070 but received a new error

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-21 09:25:44.349 ERROR 38324 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:753) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:309) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.sonatype.cs.getmetrics.GetMetricsApplication.main(GetMetricsApplication.java:43) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[get-metrics-90.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[get-metrics-90.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[get-metrics-90.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[get-metrics-90.jar:na]
Caused by: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
        at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:451) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175) ~[na:na]
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580) ~[na:na]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220) ~[na:na]
        at org.sonatype.cs.getmetrics.util.NexusIqApiConnection.executeHttpURLPostForCSV(NexusIqApiConnection.java:88) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.util.NexusIqApiConnection.retrieveCsvBasedOnPayload(NexusIqApiConnection.java:83) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.service.NexusIQSuccessMetrics.createSuccessMetricsCsvFile(NexusIQSuccessMetrics.java:66) ~[classes!/:na]
        at org.sonatype.cs.getmetrics.GetMetricsApplication.run(GetMetricsApplication.java:53) ~[classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:769) ~[spring-boot-2.6.3.jar!/:2.6.

Any help?

**Comment by rpanman-sonatype** [comment]
Hi @lexbernier - would you be able to share the config file that you are using (obviously hide real usernames and passwords).

**Comment by lexbernier** [comment]
sure, 

`metrics.successmetrics=true
metrics.applicationsevaluations=true
metrics.waivers=true
metrics.policyviolations=true
metrics.firewall=false

# amend accordingly
iq.url=http://san-stiq-prod.cscr.hp.com:8070

# For docker, comment out the above url, and use (uncomment) this
# iq.url=http://host.docker.internal:8070

# amend accordingly
iq.user=xxxxxx
iq.passwd=xxxxxxxxxxxxx

# mandatory: week, month
iq.api.sm.period=week

# mandatory: example: week=2020-W01, month=2020-01
iq.api.sm.payload.timeperiod.first="2022-W04"

# optional
iq.api.sm.payload.timeperiod.last="2022-W11"

# optional: set one of the two below to a comma-separated list
# if both omitted (the default), all organisations/applications will apply
# if both set, organisation will take precedence
iq.api.sm.payload.organisation.name=
iq.api.sm.payload.application.name=


iq.api=/api/v2
iq.api.reports=/reports/metrics
metricsDir=../iqmetrics
`

**Comment by rpanman-sonatype** [comment]
It looks like it's the quotes around 2022-W04 and 2022-W11 so if you could update to this instead then it should work:
```
# mandatory: example: week=2020-W01, month=2020-01
iq.api.sm.payload.timeperiod.first=2022-W04

# optional
iq.api.sm.payload.timeperiod.last=2022-W11
```

**Comment by lexbernier** [comment]
> It looks like it's the quotes around 2022-W04 and 2022-W11 so if you could update to this instead then it should work:
> 
> ```
> # mandatory: example: week=2020-W01, month=2020-01
> iq.api.sm.payload.timeperiod.first=2022-W04
> 
> # optional
> iq.api.sm.payload.timeperiod.last=2022-W11
> ```

Seemed to have fixed issue. Thanks
