### ISSUE TITLE
Exception on waiver request

### ISSUE THREAD

**Issue by rpanman-sonatype** [sonatype-nexus-community/nexusiq-successmetrics#89]
```
at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252) ~[javax.json-1.1.jar!/:1.1]
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257) ~[javax.json-1.1.jar!/:1.1]
	at org.sonatype.cs.getmetrics.reports.Waivers.doWaivers(Waivers.java:74) ~[classes!/:na]
	at org.sonatype.cs.getmetrics.reports.Waivers.getWaiversInformationFromData(Waivers.java:36) ~[classes!/:na]
	at org.sonatype.cs.getmetrics.reports.Waivers.makeCsvFile(Waivers.java:24) ~[classes!/:na]
	at org.sonatype.cs.getmetrics.service.NexusIQApiService.makeReport(NexusIQApiService.java:60) ~[classes!/:na]
	at org.sonatype.cs.getmetrics.GetMetricsApplication.run(GetMetricsApplication.java:80) [classes!/:na]
```

**Comment by rpanman-sonatype** [comment]
Fixed in PR #91
